//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/IA_Player.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @IA_Player: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @IA_Player()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IA_Player"",
    ""maps"": [
        {
            ""name"": ""Pluto"",
            ""id"": ""e1a70e1f-bbe2-4dbd-886b-a8f30ffe15e8"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""05c5b1d4-ba23-4ec7-aee6-f580f8750c4e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Gravity"",
                    ""type"": ""Button"",
                    ""id"": ""d3631fe0-e97e-4e86-8835-2b1aac341f43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""a07b96e7-e399-4a2a-acab-28787ba327a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2569b8e3-0e4a-41cf-8526-3d4b408286c6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db38263f-2c95-44df-b6ef-be20f85a1eb8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gravity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7e53ca0f-487b-4875-a4b5-93b70e87c016"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c706a6b0-f8e5-4013-8339-b8e8a113d422"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c609e3f5-06e8-4d2f-8d38-928c3d96fc15"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bcdc45a2-89da-432e-86f7-82419e07e37f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""401cd120-5d87-4a21-a363-4a8843121e42"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f5207bd4-a3da-4dce-be1a-c62946cd0dfc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""641ac588-cda0-4ec0-b830-c84eeecb2e52"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54178d77-ce4e-4ae0-acc0-d0c9af9032e8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Resettable"",
            ""id"": ""857673b9-fdf2-4597-9a0f-e8c8a0569004"",
            ""actions"": [
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""4016aeab-85fb-4310-a795-285b37817dd7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f12c3c16-3c6a-49c0-8b50-10406bd65c1f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a35489c6-7043-4304-8235-d65429b05703"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Pluto
        m_Pluto = asset.FindActionMap("Pluto", throwIfNotFound: true);
        m_Pluto_Move = m_Pluto.FindAction("Move", throwIfNotFound: true);
        m_Pluto_Gravity = m_Pluto.FindAction("Gravity", throwIfNotFound: true);
        m_Pluto_Interact = m_Pluto.FindAction("Interact", throwIfNotFound: true);
        // Resettable
        m_Resettable = asset.FindActionMap("Resettable", throwIfNotFound: true);
        m_Resettable_Reset = m_Resettable.FindAction("Reset", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Pluto
    private readonly InputActionMap m_Pluto;
    private List<IPlutoActions> m_PlutoActionsCallbackInterfaces = new List<IPlutoActions>();
    private readonly InputAction m_Pluto_Move;
    private readonly InputAction m_Pluto_Gravity;
    private readonly InputAction m_Pluto_Interact;
    public struct PlutoActions
    {
        private @IA_Player m_Wrapper;
        public PlutoActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Pluto_Move;
        public InputAction @Gravity => m_Wrapper.m_Pluto_Gravity;
        public InputAction @Interact => m_Wrapper.m_Pluto_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Pluto; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlutoActions set) { return set.Get(); }
        public void AddCallbacks(IPlutoActions instance)
        {
            if (instance == null || m_Wrapper.m_PlutoActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlutoActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Gravity.started += instance.OnGravity;
            @Gravity.performed += instance.OnGravity;
            @Gravity.canceled += instance.OnGravity;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
        }

        private void UnregisterCallbacks(IPlutoActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Gravity.started -= instance.OnGravity;
            @Gravity.performed -= instance.OnGravity;
            @Gravity.canceled -= instance.OnGravity;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
        }

        public void RemoveCallbacks(IPlutoActions instance)
        {
            if (m_Wrapper.m_PlutoActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlutoActions instance)
        {
            foreach (var item in m_Wrapper.m_PlutoActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlutoActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlutoActions @Pluto => new PlutoActions(this);

    // Resettable
    private readonly InputActionMap m_Resettable;
    private List<IResettableActions> m_ResettableActionsCallbackInterfaces = new List<IResettableActions>();
    private readonly InputAction m_Resettable_Reset;
    public struct ResettableActions
    {
        private @IA_Player m_Wrapper;
        public ResettableActions(@IA_Player wrapper) { m_Wrapper = wrapper; }
        public InputAction @Reset => m_Wrapper.m_Resettable_Reset;
        public InputActionMap Get() { return m_Wrapper.m_Resettable; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ResettableActions set) { return set.Get(); }
        public void AddCallbacks(IResettableActions instance)
        {
            if (instance == null || m_Wrapper.m_ResettableActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ResettableActionsCallbackInterfaces.Add(instance);
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
        }

        private void UnregisterCallbacks(IResettableActions instance)
        {
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
        }

        public void RemoveCallbacks(IResettableActions instance)
        {
            if (m_Wrapper.m_ResettableActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IResettableActions instance)
        {
            foreach (var item in m_Wrapper.m_ResettableActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ResettableActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ResettableActions @Resettable => new ResettableActions(this);
    public interface IPlutoActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnGravity(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IResettableActions
    {
        void OnReset(InputAction.CallbackContext context);
    }
}
